[package]
name = "drl"
version = "0.1.0"
authors = ["XiangXu <xuxiang@sensetime.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.5.0"
rand = "0.8.4"
plotlib = "0.5.1"
random_choice = "*"
